version: "3.6"

services:
  balancer-server:
    image: anroe/nginx-geoip2
    volumes:
      - ./config/load-balancer/nginx.conf:/etc/nginx/nginx.conf
      - ./geo-ip/GeoLite2-Country.mmdb:/var/lib/GeoIP/GeoLite2-Country.mmdb
    ports:
      - 80:80

  app_uk:
    image: nginx:latest
    volumes:
      - ./config/servers/uk/nginx.conf:/etc/nginx/nginx.conf
      - ./app/uk/index.html:/usr/share/nginx/html/index.html

  app_us_1:
    image: nginx:latest
    volumes:
      - ./config/servers/us/nginx.conf:/etc/nginx/nginx.conf
      - ./app/us-1/index.html:/usr/share/nginx/html/index.html

  app_us_2:
    image: nginx:latest
    volumes:
      - ./config/servers/us/nginx.conf:/etc/nginx/nginx.conf
      - ./app/us-2/index.html:/usr/share/nginx/html/index.html

  app_default:
    image: nginx:latest
    volumes:
      - ./config/servers/default/nginx.conf:/etc/nginx/nginx.conf
      - ./app/default/index.html:/usr/share/nginx/html/index.html
